#ifndef IMAGE_FILENAMES_H
#define IMAGE_FILENAMES_H


const char* image_files[] = {
    "/bend-angle.jpg",
    "/bend-horiz.jpg",
    "/bend-top.jpg",
    "/crouch-angle.jpg",
    "/crouch-horiz.jpg",
    "/crouch-top.jpg",
    "/damage-angle.jpg",
    "/damage-horiz.jpg",
    "/damage-top.jpg",
    "/faint-angle.jpg",
    "/faint-horiz.jpg",
    "/faint-top.jpg",
    "/fight-angle.jpg",
    "/fight-horiz.jpg",
    "/fight-top.jpg",
    "/follow-angle.jpg",
    "/follow-horiz.jpg",
    "/follow-top.jpg",
    "/gather-angle.jpg",
    "/gather-horiz.jpg",
    "/gather-top.jpg",
    "/jump-angle.jpg",
    "/jump-horiz.jpg",
    "/jump-top.jpg",
    "/meet-angle.jpg",
    "/meet-horiz.jpg",
    "/meet-top.jpg",
    "/overtake-angle.jpg",
    "/overtake-horiz.jpg",
    "/overtake-top.jpg",
    "/rob-angle.jpg",
    "/rob-horiz.jpg",
    "/rob-top.jpg",
    "/run-angle.jpg",
    "/run-horiz.jpg",
    "/run-top.jpg",
    "/together-angle.jpg",
    "/together-horiz.jpg",
    "/together-top.jpg",
    "/walk-angle.jpg",
    "/walk-horiz.jpg",
    "/walk-top.jpg",
    "/wander-angle.jpg",
    "/wander-horiz.jpg",
    "/wander-top.jpg",
    NULL,

};

#endif // IMAGE_FILENAMES_H
